### ISSUE TITLE
Running list: requests the API will need to support for the end to end tests

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#60]
### Context

I've created a set of end to end tests for us to implement: #49

This issue will list all of the various requests the API will need to support for the end to end tests. This may include the same route being used for different purposes in order to highlight special parameter the route may need to support.

These may serve as good fuel for unit tests for API as well.

### Endpoints:
- [x] Create account with grant id for personal account
- [x] Create account without grant id
- [ ] List resource on personal organization
- [ ] List resource on non-personal organization
- [ ] Create non-personal organization with grant id
- [ ] Invite user to an organization (see https://github.com/AlexsLemonade/resources-portal/issues/53)
- [ ] Accept invitation to join organization.
- [ ] Grant permissions to organization member
- [ ] Remove permissions from organization member
- [ ] Change notification settings.
- [ ] Search resources
- [ ] Request a resource
- [ ] Approve a request
- [ ] Reviewer marks request fulfilled (see https://github.com/AlexsLemonade/resources-portal/issues/55)
- [ ] Requester marks request fulfilled (see https://github.com/AlexsLemonade/resources-portal/issues/55)

**Comment by kurtwheeler** [comment]
I think this issue has been well implemented! We no longer need this to track things.
