### ISSUE TITLE
Roadmap for the frontend

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/resources-portal#63]
This is a proposed plan for how we might approach the development of the resources portal. I took some notes in a [mind map](https://miro.com/app/board/o9J_ku-Z6yc=/) with the dependencies of each one of these items.

For each resource type will need the following:
- a template to display the resource as a search result
- a details page
- workflow to list a new instance of the resource
- workflow to import a new instance of the resource

I think we should initially focus on a single resource type, and build the entire application to support it in an extensible way so that we can add other resource types afterward. I propose that we **start with GEO** since it's more familiar to us and we can build an importer for it.

A possible plan to implement the resources portal with a single resource type could be divided into three stages:

## 1. Add barebones

- [x] Add some boilerplate for the project, this should also set the structure for where we'll put the components and each individual pages. #65 

- [x] Add a layout component that will be reused by all pages, in NextJS this goes into a custom `App` component #66

- [x] Start creating components that will be useful. We could consider using [Storybook](https://storybook.js.org/) to develop these components independently. #67
  - [x] Tab component #68
  - [x] Table #69
  - [x] File drop zone #70
  - [x] Buttons, dropdowns, text area, etc. https://github.com/AlexsLemonade/resources-portal/issues/36

## 2. Start adding individual pages

- [ ] Import resources page (only GEO for now): `/resources/import`

- [ ] List a resource page (only GEO for now): `/resources/add`

- [ ] Search resources page: `/search/?q=mouse`. Initially, we can aim only to have the search input and the search results below and leave the space for the filters and other components. https://github.com/AlexsLemonade/resources-portal/issues/91

- [ ] View resource page: `/resources/RESOURCE_ID`. Initially, we can add only the first two tabs: Resource Details and Publication Information. https://github.com/AlexsLemonade/resources-portal/issues/92
 
- [ ] Request resources: `/resources/RESOURCE_ID/request` #93 

## 3. Additional details

(Most of these are dependant on the pages before)

- [Search page] Add filters

- [Search page] Pagination *(designs need to be updated)*

- [Search page] Add dropdown next to the search input to search individual resource types

- [View resource] Add contact submitter Tab

- [View resource] Add request requirements tab

- [View resource] Add previews of related resources

- [View resource] Add cite link that focuses the publication information tab

- [List/Import page] Ability to save draft https://github.com/AlexsLemonade/resources-portal/issues/48

----

Each one of the items in these groups can be done in parallel. And afterward, we can add other resource types one by one.

We also need designs for the following pages. @dvenprasad are there any others?

- My Account pages
- Help Page
- Landing page

After having the My Account page we can start thinking of user pages, notifications, etc.

@davidsmejia @kurtwheeler @cgreene feel free to edit this or add any comments. If you think this makes sense I can start creating issues.

**Comment by kurtwheeler** [comment]
Wow this is really great!! So if I understand you correctly, we can do the things in `Add barebones` in parallel, but we'll need to have them done before starting in on `Start adding individual pages`. I'm thinking that for this sprint we could make issues for each of:
* Add some boilerplate for the project, this should also set the structure for where we'll put the components and each individual pages.
* Add a layout component that will be reused by all pages, in NextJS this goes into a custom App component
* Create component for Tab component
* Create component for Table
* Create component for File drop zone
* Crete components for Buttons, dropdowns, text area, etc. #36 

Does that seem like it'd be a good idea to you @arielsvn? If so could you make some issues for each of those tasks before the spring planning meeting at 11? (Phil should be in soon so I probably won't have a chance.)

**Comment by dvenprasad** [comment]
Yes, there are more pages:
- Request tracking dashboard
- Reviewing request materials and decision page

Form to: 
- upload signed MTAs
- Specify shipping methods

**Comment by kurtwheeler** [comment]
I think that we're well past where this document was planning.
